{% set version = "12.4.0" %}

package:
  name: cuda-visual-tools
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - cuda-nsight 12.4.99               # [not (aarch64 or win)]
    - nsight-compute 2024.1.0.13
    - cuda-nvml-dev 12.4.99
    - cuda-nvvp 12.4.99                 # [not aarch64]
    - cuda-libraries-dev {{ version }}

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Contains the visual tools to debug and profile CUDA applications
  description: |
    Contains the visual tools to debug and profile CUDA applications
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
